version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: jay75chauhan/node_crud_docker:1.0.0
    ports:
      - "3000:3000"
    environment:
      - PG_DB=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
